---
title: "OPAM 2025: Latent Variable Analysis"
author: Your Name
date: today
theme: default
format:
  html:
    code-fold: true
    code-tools: true
    code-link: true
    toc: true
    toc-depth: 1
    toc-location: left
    page-layout: full
    df-print: paged
execute:
  error: true
  warning: true
self-contained: true
editor_options:
  chunk_output_type: console
editor: visual
---

# Setup

## Required Packages

```{r}
#| warning: false
#| code-fold: false

library(here)
library(readr)
library(dplyr)
library(sjPlot)
library(psych)
library(lavaan)
library(semoutput)
library(semTools)
```

# Data

## Import Data

```{r}
#| message: false
#| code-fold: false

data_imported <- read_csv(here("Martin_etal_DataSet_3.csv"))
```

## Get Data Ready for Models

```{r}
#| code-fold: false

data <- select(data_imported, -Subject)
```

# Descriptives

```{r}
sem_descriptives(data)
```

# Correlations

```{r}
tab_corr(data, na.deletion = "pairwise", show.p = FALSE)
```

# CFA

## Model

```{r}
#| code-fold: false


```

## Results

```{r}
summary(fit, fit.measures = TRUE, standardized = TRUE)
```

```{r}
sem_tables(fit)
```

# SEM: Correlated Predictors

## Model

```{r}
#| code-fold: false


```

## Results

```{r}
summary(fit, fit.measures = TRUE, standardized = TRUE)
```

```{r}
sem_tables(fit)
```

# Footer

::: panel-tabset
## Session Info

```{r}
sessionInfo()
```

## Citations

```{r}
lapply(names(sessionInfo()$otherPkgs), citation)
```

## CSS Styling

```{css}
#| code-fold: false

:root {
  --color-primary: #005098;
  --color-accent: #96834a;
  --color-border: #CBB879;
  --color-border-light: #ECE5D7;
  --color-text: #495057;
}

.tab-content {
  border-style: none;
}

h1 {
  color: var(--color-primary);
}

h2 {
  color: var(--color-accent) !important;
  font-weight: 600 !important;
}

a {
  color: var(--color-primary);
}

a:hover {
  color: var(--color-accent) !important;
}

.quarto-title-meta-heading {
  color: var(--color-accent);
  font-weight: 600 !important;
}

.sidebar nav[role=doc-toc] ul>li>a,
.sidebar nav[role=doc-toc] ul>li>ul>li>a {
  color: var(--color-primary) !important;
  border-left: 2px solid var(--color-border-light);
}

.sidebar nav[role=doc-toc] ul>li>a.active,
.sidebar nav[role=doc-toc] ul>li>ul>li>a.active {
  color: var(--color-primary) !important;
  font-weight: 600;
  border-left: 2px solid var(--color-border);
}

.sidebar nav[role=doc-toc] ul>li>a:hover,
.sidebar nav[role=doc-toc] ul>li>ul>li>a:hover {
  color: var(--color-primary) !important;
  font-weight: 600;
  border-left: 2px solid var(--color-border);
}

.nav-link {
  color: var(--color-text);
}

.nav-tabs .nav-link.active,
.nav-tabs .nav-item.show .nav-link {
  color: var(--color-accent) !important;
}

.code-tools-button {
  color: var(--color-accent) !important;
}

.dropdown-toggle {
  color: var(--color-primary) !important;
}
```
:::
